name: CI/CD Pipeline

on: # update dockerhub image on push or pull_request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # create ubuntu vm that handles building the new docker image and pushes it to dockerhub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # load code from repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # sets up docker builder

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # login to duckerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4 # build and push to dockerhub
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kubernetes_assignment:latest
